%% Module: app
%% Depends on: recommendation_engine/mood_track_finder, search/autocomplete, utils/validators, flask, functools, git, hashlib, hmac, json, logging, os, recommendation_engine, spotipy, werkzeug/exceptions
graph TD
app[app] --> recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder]
app[app] --> search_autocomplete[search/autocomplete]
app[app] --> utils_validators[utils/validators]
app[app] --> flask[flask]
app[app] --> functools[functools]
app[app] --> git[git]
app[app] --> hashlib[hashlib]
app[app] --> hmac[hmac]
app[app] --> json[json]
app[app] --> logging[logging]
app[app] --> os[os]
app[app] --> recommendation_engine[recommendation_engine]
app[app] --> spotipy[spotipy]
app[app] --> werkzeug_exceptions[werkzeug/exceptions]
