%% Module: scripts/get_isrc_code
%% Depends on: oauth2_musicbrainz, pprint, search_playground
graph TD
scripts_get_isrc_code[scripts/get_isrc_code] --> oauth2_musicbrainz[oauth2_musicbrainz]
scripts_get_isrc_code[scripts/get_isrc_code] --> pprint[pprint]
scripts_get_isrc_code[scripts/get_isrc_code] --> search_playground[search_playground]
