%% Module: wsgi_pythonanywhere
%% Depends on: app, dotenv, sys
graph TD
wsgi_pythonanywhere[wsgi_pythonanywhere] --> app[app]
wsgi_pythonanywhere[wsgi_pythonanywhere] --> dotenv[dotenv]
wsgi_pythonanywhere[wsgi_pythonanywhere] --> sys[sys]
