%% Module: recommendation_engine/mood_track_finder
%% Depends on: pprint, random, spotipy, statistics, typing, werkzeug/exceptions
graph TD
recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder] --> pprint[pprint]
recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder] --> random[random]
recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder] --> spotipy[spotipy]
recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder] --> statistics[statistics]
recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder] --> typing[typing]
recommendation_engine_mood_track_finder[recommendation_engine/mood_track_finder] --> werkzeug_exceptions[werkzeug/exceptions]
