%% Module: scripts/get_acoustic_brainz_data
%% Depends on: json, os, pathlib, pickle, pprint, tarfile
graph TD
scripts_get_acoustic_brainz_data[scripts/get_acoustic_brainz_data] --> json[json]
scripts_get_acoustic_brainz_data[scripts/get_acoustic_brainz_data] --> os[os]
scripts_get_acoustic_brainz_data[scripts/get_acoustic_brainz_data] --> pathlib[pathlib]
scripts_get_acoustic_brainz_data[scripts/get_acoustic_brainz_data] --> pickle[pickle]
scripts_get_acoustic_brainz_data[scripts/get_acoustic_brainz_data] --> pprint[pprint]
scripts_get_acoustic_brainz_data[scripts/get_acoustic_brainz_data] --> tarfile[tarfile]
